### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by mampersat** [mampersat/metar-map#1]
Traceback (most recent call last):
  File "main.py", line 103, in <module>
  File "main.py", line 37, in get_metars
  File "urequests.py", line 28, in text
  File "urequests.py", line 23, in content
  File "urequests.py", line 20, in content
MemoryError: memory allocation failed, allocating 4352 bytes
MicroPython v1.11-8-g48dcbbe60 on 2019-05-29; ESP module with ESP8266
Type "help()" for more information.

**Comment by helloworld123YY** [comment]
got same errors
> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 69, in <module>
  File "<stdin>", line 50, in get_metars
  File "urequests.py", line 116, in get
  File "urequests.py", line 55, in request
OSError: -2
